version: '3'
services:
  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_USER:  ${{ Development.DATABASE_USER }}
      POSTGRES_PASSWORD: ${{ Development.DATABASE_PASSWORD }}
      POSTGRES_DB: ${{ Development.DATABASE_NAME }}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django_crud:
    build: .
    command: ["sh", "-c", "coverage run manage.py test && coverage report -m"]
    volumes:
      - .:/app
    depends_on:
      - postgres_db

volumes:
  postgres_data:
