version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user
    ports:
      - "5442:5442"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: ["sh", "-c", "coverage run manage.py test && coverage report -m"]
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data:
