# Generated by Django 4.2.4 on 2023-08-22 17:12

import crud.models.user
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "contact_number",
                    models.CharField(
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("email_id", models.EmailField(max_length=254, unique=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("dob", models.DateField(validators=[crud.models.user.validate_age])),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_profile",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["contact_number"], name="contact_idx"),
                    models.Index(fields=["email_id"], name="email_idx"),
                ],
            },
        ),
    ]
