name: Test and Coverage

on: [push]

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Drop and recreate database
      run: |
        docker-compose down
        docker-compose up -d
        docker-compose run web python manage.py migrate

    - name: Build and run Docker Compose
      run: |
        docker-compose up -d
        docker-compose run web

    - name: Check coverage
      run: |
        COVERAGE_PERCENT=$(docker-compose run web coverage report | grep TOTAL | awk '{print $NF}')
        if [[ $(bc <<< "$COVERAGE_PERCENT >= 80") -eq 1 ]]; then
          echo "Coverage is greater than or equal to 80%"
        else
          echo "Coverage is below 80%"
          exit 1
        fi