# To Check the test coverage report of the project and its test health
name: Test and Coverage
on: [pull_request, push]
jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: user
        ports:
          - "5433:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Build and run Docker Compose
      run: |
        docker-compose up -d
        docker-compose run django_crud bash -c "coverage run manage.py test && coverage report -m --fail-under=80"


