# To Check the test coverage report of the project and its test health
name: Test and Coverage
on: [pull_request, push]
jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydb
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests and coverage
      run: |
        coverage run manage.py test
        COVERAGE_PERCENT=$(coverage report -m | grep TOTAL | awk '{print $NF}' | tr -d '%')
        echo "Test coverage: ${COVERAGE_PERCENT}%" 

        if [ $COVERAGE_PERCENT -lt 80 ]; then
            echo "Test coverage is below 80%: ${COVERAGE_PERCENT}%"
            exit 1
        fi
